name: Publish NuGet

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          8.x
          9.x
    - name: Build
      run: dotnet build -c Release Source/Salix.AspNetCore.TitlePage/Salix.AspNetCore.TitlePage.csproj

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
